apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-helm-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/lukeabela38/stunning-octo-fishstick.git'
      revision: HEAD
      directories:
      - path: infrastructure/argocd/apps
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/lukeabela38/stunning-octo-fishstick.git'
        targetRevision: HEAD
        path: 'traefik'
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: https://default.svc
        # Drops the "dev-" or "prod-" prefix to target the correct namespace
        namespace: '{{path.basename}}' 
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
