apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - platform/traefik/app.yaml
  - platform/cert-manager/app.yaml
  - platform/cluster-issuer/letsencrypt.yaml
  - platform/argocd/ingress.yaml
  - apps/demo