apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # FIX: Ensure the domain is strictly raw.githubusercontent.com (with the .raw suffix structure)
  - https://githubusercontent.com

