apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Pulls the official, exact version of ArgoCD declaratively
  - https://githubusercontent.com

# You can easily append configuration tweaks here later (like ConfigMaps)
